scripts: add zboot support to extract-vmlinux
Zboot compressed kernel images are used for arm kernels on various
distros.

extract-vmlinux fails with those kernels because the wrapped image is
another PE. While this could be a bit confusing, the tools primary
purpose of unwrapping and decompressing the contained vmlinux image
makes it the obvious place for this functionality.

Add a 'file' check in check_vmlinux() that detects a contained PE
image before trying readelf. Recent file implementations output
something like:

"Linux kernel ARM64 boot executable Image, little-endian, 4K pages"

Which is also a stronger statement than readelf provides so drop that
part of the comment. At the same time this means that kernel images
which don't appear to contain a compressed image will be returned
rather than reporting an error. Which matches the behavior for
existing ELF files.

Signed-off-by: Jeremy Linton <jeremy.linton@arm.com>
Cc: Ard Biesheuvel <ardb@kernel.org>

diff --git a/scripts/extract-vmlinux b/scripts/extract-vmlinux
--- a/scripts/extract-vmlinux
+++ b/scripts/extract-vmlinux
@@ -12,10 +12,11 @@
 
 check_vmlinux()
 {
-	# Use readelf to check if it's a valid ELF
-	# TODO: find a better to way to check that it's really vmlinux
-	#       and not just an elf
-	readelf -h $1 > /dev/null 2>&1 || return 1
+	file $1 |grep 'Linux kernel.*boot executable Image' > /dev/null
+	if [ "$?" -ne "0" ]; then
+		# Use readelf to check if it's a valid ELF, if 'file' fails
+		readelf -h $1 > /dev/null 2>&1 || return 1
+	fi
 
 	cat $1
 	exit 0
